import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFileSync, existsSync, statSync } from 'node:fs';
import { join, extname } from 'node:path';
const DIST='/home/user/UsalamaSMS/dist';
const T={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const s=createServer((q,r)=>{const u=q.url.split('?')[0];let f=join(DIST,u);if(!existsSync(f)||u==='/'||statSync(f).isDirectory())f=join(DIST,'index.html');try{const b=readFileSync(f);r.writeHead(200,{'content-type':T[extname(f)]??'text/html'});r.end(b);}catch{r.writeHead(404);r.end('no');}});
await new Promise(r=>s.listen(0,r));
const B=`http://localhost:${s.address().port}`;
const br=await chromium.launch();
const ctx=await br.newContext({viewport:{width:1440,height:900},serviceWorkers:'block'});
const p=await ctx.newPage();
let payload={};
await p.route('**/api/v1/**',r=>r.fulfill({status:200,contentType:'application/json',body:'{}'}));
await p.route('**/api/v1/auth/refresh',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({accessToken:'s',refreshToken:'s2',role:'SAFETY_MANAGER',orgId:'o1'})}));
await p.route('**/api/v1/sms/training*',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(payload)}));
const load=async()=>{await p.goto(B+'/sms',{waitUntil:'networkidle'});
 await p.evaluate(()=>{localStorage.setItem('usalamasms.session',JSON.stringify({role:'SAFETY_MANAGER',orgId:'o1'}));localStorage.setItem('usalamasms.refresh','stub');});
 await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(1000);
 return p.evaluate(()=>document.body.innerText);};
payload={scope:'org',training:[],curriculum:[{userId:'u1',name:'A. Mwangi',required:['SMS initial'],held:[],gaps:['SMS initial'],unrecognised:[]}],curriculumVerifiedAgainstPrimary:true,curriculumInstrument:'CAA-AC-SMS011'};
let t=await load();
console.log('ZERO RECORDS + GAP:',JSON.stringify({gap:/no record covers/i.test(t),prov:t.includes('CAA-AC-SMS011')}));
console.log('  what the page fetched:', await p.evaluate(async()=>(await (await fetch('/api/v1/sms/training')).text()).slice(0,120)));
const at=t.indexOf('4.1'); console.log('  4.1 text:', t.slice(at,at+240).replace(/\s+/g,' '));
await br.close(); s.close();
