/* ============================================================
   CHANGING YOUR OWN NAME, AND YOUR OWN PASSWORD.

   NEITHER EXISTED, AND THE SECOND ONE IS THE SERIOUS HALF.

   The administrator reset route ends its response with "Shown once.
   Hand it over directly and have them change it." There was no way to
   change it. A temporary password generated by an administrator and
   handed over in person WAS the permanent password of that account —
   an instruction with a wording and no mechanism, which is the same
   defect the demo-password rotation had before `--rotate` was written.

   Worse here than there: that was a demo, this is an operator's safety
   officer holding a credential a second person has seen and cannot stop
   knowing, on an account that reads every narrative in the operator.

   WHAT THESE GUARD, in the order they would bite:

     1. THE CURRENT PASSWORD IS PROVED. An access token lives fifteen
        minutes and gets left on a shared handset in a ready room. A
        change-password route trusting the token alone turns a borrowed
        screen into a permanent account takeover.

     2. EVERY SESSION IS REVOKED. A refresh token minted before the
        change still mints access tokens after it, so a change that
        leaves one alive has ended nothing — the sentence CLAUDE.md
        writes about rotation, applied to the route a user can reach.

     3. A FAILED CHANGE CHANGES NOTHING. The old password must still
        work after a refusal, or a wrong guess has locked somebody out
        of a safety record.

     4. THE CREDENTIAL NEVER REACHES THE AUDIT CHAIN. Not the old one,
        not the new one, not a prefix.

     5. TENANCY. The route acts on the caller, never on an id somebody
        sends.
   ============================================================ */

import { describe, it, expect, beforeAll, afterAll, beforeEach } from "vitest";
import jwt from "jsonwebtoken";
import argon2 from "argon2";
import type { FastifyInstance } from "fastify";
import { prisma, reset, migrate, disconnect, hasDatabase } from "./db.setup";

const JWT_SECRET = "integration-test-secret-not-a-real-one";
process.env["JWT_SECRET"] = JWT_SECRET;
process.env["DEIDENT_SALT"] = "integration-test-salt";
process.env["LOG_LEVEL"] = "silent";

const CURRENT = "the-current-password-1";
const REPLACEMENT = "a-quite-different-password-2";

let app: FastifyInstance;
let orgId: string;
let userId: string;
let otherOrgId: string;
let otherUserId: string;

const tokenFor = (sub: string, org: string, role: string): string =>
  jwt.sign({ sub, org, role, typ: "access" }, JWT_SECRET, {
    algorithm: "HS256", expiresIn: "15m", issuer: "usalamasms",
  });

describe.skipIf(!hasDatabase)("your own name and your own password", () => {
  beforeAll(async () => {
    migrate();
    const { build } = await import("../../apps/api/src/server");
    app = await build();
    await app.ready();
  });

  afterAll(async () => {
    await app?.close();
    await disconnect();
  });

  beforeEach(async () => {
    await reset();
    const hash = await argon2.hash(CURRENT, { type: argon2.argon2id });
    const org = await prisma().org.create({ data: { name: "Design Partner AOC" } });
    orgId = org.id;
    userId = (
      await prisma().user.create({
        data: {
          orgId, email: "officer@a.test", passwordHash: hash,
          name: "Amina Odhiambo", role: "SAFETY_OFFICER" as never,
        },
      })
    ).id;

    const other = await prisma().org.create({ data: { name: "Somebody Else AOC" } });
    otherOrgId = other.id;
    otherUserId = (
      await prisma().user.create({
        data: {
          orgId: otherOrgId, email: "officer@b.test", passwordHash: hash,
          name: "Someone Else", role: "SAFETY_OFFICER" as never,
        },
      })
    ).id;
  });

  const me = () => tokenFor(userId, orgId, "SAFETY_OFFICER");

  let probe = 0;
  const headers = () => ({
    authorization: `Bearer ${me()}`,
    "x-nf-client-connection-ip": `198.51.100.${++probe}`,
  });

  const getMe = () =>
    app.inject({ method: "GET", url: "/api/v1/auth/me", headers: headers() });

  const patchMe = (body: unknown) =>
    app.inject({ method: "PATCH", url: "/api/v1/auth/me", headers: headers(), payload: body as never });

  const changePassword = (body: unknown) =>
    app.inject({
      method: "POST", url: "/api/v1/auth/password", headers: headers(), payload: body as never,
    });

  const storedHash = async (id = userId) =>
    (await prisma().user.findUnique({ where: { id }, select: { passwordHash: true } }))!.passwordHash;

  /* ---------------------------- who you are ---------------------------- */

  it("says who the person is, not only which tenant they are in", async () => {
    const body = (await getMe()).json();
    expect(body.name).toBe("Amina Odhiambo");
    expect(body.email).toBe("officer@a.test");
    expect(body.orgName).toBe("Design Partner AOC");
  });

  /* THE SERVER SAYS WHAT THE CALLER HOLDS, so the account page never
     re-derives a role's rights — the same rule the queue follows when
     it returns which moves a caller may make. */
  it("returns the caller's permissions so the screen need not re-derive them", async () => {
    const body = (await getMe()).json();
    expect(Array.isArray(body.permissions)).toBe(true);
    expect(body.permissions.length).toBeGreaterThan(0);
    expect(body.permissions).toContain("report.create");
  });

  it("never returns the password hash", async () => {
    expect((await getMe()).body).not.toContain("$argon2");
    expect((await getMe()).body).not.toContain("passwordHash");
  });

  /* ------------------------------ the name ------------------------------ */

  it("changes the name and reads it back", async () => {
    expect((await patchMe({ name: "Amina Odhiambo-Kimani" })).statusCode).toBe(200);
    expect((await getMe()).json().name).toBe("Amina Odhiambo-Kimani");
  });

  it("refuses a name too short to be one, and changes nothing", async () => {
    expect((await patchMe({ name: "A" })).statusCode).toBe(400);
    expect((await getMe()).json().name).toBe("Amina Odhiambo");
  });

  /* A name is what appears against a disposition an investigator later
     reads, so both sides are the fact that answers whether two entries
     were the same person. */
  it("audits both sides of the rename", async () => {
    await patchMe({ name: "Amina Odhiambo-Kimani" });
    const entry = await prisma().auditLog.findFirst({
      where: { orgId, action: "user.profile.update" }, orderBy: { seq: "desc" },
    });
    const detail = entry!.detail as { name?: { from: string; to: string } };
    expect(detail.name?.from).toBe("Amina Odhiambo");
    expect(detail.name?.to).toBe("Amina Odhiambo-Kimani");
  });

  /* THE EMAIL IS THE LOGIN IDENTIFIER and changing it is an account
     migration rather than a profile edit. A payload that carried one
     must not quietly become one. */
  it("does not let the email be changed by sending one", async () => {
    await patchMe({ name: "Amina Odhiambo-Kimani", email: "somebody@else.test" });
    expect((await getMe()).json().email).toBe("officer@a.test");
  });

  /* ---------------------------- the password ---------------------------- */

  it("changes the password when the current one is proved", async () => {
    const before = await storedHash();
    const res = await changePassword({ currentPassword: CURRENT, newPassword: REPLACEMENT });

    expect(res.statusCode).toBe(200);
    expect(await storedHash(), "the hash did not change").not.toBe(before);
    expect(await argon2.verify(await storedHash(), REPLACEMENT)).toBe(true);
  });

  /* PROPERTY 1. Without this, a token left on a shared handset is a
     permanent account takeover. */
  it("REFUSES without the current password, and changes nothing", async () => {
    const before = await storedHash();
    const res = await changePassword({ currentPassword: "not-the-password", newPassword: REPLACEMENT });

    expect(res.statusCode).toBe(403);
    expect(await storedHash()).toBe(before);
    /* PROPERTY 3. A wrong guess must not lock somebody out. */
    expect(await argon2.verify(await storedHash(), CURRENT)).toBe(true);
  });

  it("refuses a new password shorter than the sign-up floor", async () => {
    const before = await storedHash();
    expect(
      (await changePassword({ currentPassword: CURRENT, newPassword: "short" })).statusCode,
    ).toBe(400);
    expect(await storedHash()).toBe(before);
  });

  /* Somebody changing a credential they believe is known has changed
     nothing by setting it back to itself, and a 200 would tell them
     they had. */
  it("refuses setting the password to the one it already is", async () => {
    const res = await changePassword({ currentPassword: CURRENT, newPassword: CURRENT });
    expect(res.statusCode).toBe(400);
    expect(res.json().error).toBe("unchanged");
  });

  /* PROPERTY 2, and it is the whole point of changing a password
     somebody else may know. */
  it("revokes every live session for the account", async () => {
    const live = async () =>
      prisma().refreshToken.count({ where: { userId, revokedAt: null } });

    await prisma().refreshToken.createMany({
      data: [
        { userId, tokenHash: "hash-one", expiresAt: new Date(Date.now() + 86_400_000) },
        { userId, tokenHash: "hash-two", expiresAt: new Date(Date.now() + 86_400_000) },
      ],
    });
    expect(await live()).toBe(2);

    await changePassword({ currentPassword: CURRENT, newPassword: REPLACEMENT });
    expect(await live(), "a session survived a password change").toBe(0);
  });

  /* And a REFUSED change must not revoke anything — otherwise a wrong
     guess signs somebody out of every device they own. */
  it("revokes nothing when the change is refused", async () => {
    await prisma().refreshToken.create({
      data: { userId, tokenHash: "hash-three", expiresAt: new Date(Date.now() + 86_400_000) },
    });
    await changePassword({ currentPassword: "wrong", newPassword: REPLACEMENT });
    expect(await prisma().refreshToken.count({ where: { userId, revokedAt: null } })).toBe(1);
  });

  /* PROPERTY 4. The act, never the credential. */
  it("records the change without recording either password", async () => {
    await changePassword({ currentPassword: CURRENT, newPassword: REPLACEMENT });
    const entry = await prisma().auditLog.findFirst({
      where: { orgId, action: "auth.password.change" },
    });
    expect(entry, "a password change left no trace in the chain").not.toBeNull();

    /* `seq` is a BigInt, which JSON.stringify refuses. Replaced rather
       than the entry narrowed, because narrowing to the columns I
       expect is exactly how a credential in an unexpected column would
       slip past this assertion. */
    const serialised = JSON.stringify(entry, (_k, v) =>
      typeof v === "bigint" ? v.toString() : v,
    );
    expect(serialised).not.toContain(CURRENT);
    expect(serialised).not.toContain(REPLACEMENT);
    expect(serialised).not.toContain("$argon2");
  });

  /* PROPERTY 5. The route acts on the token's subject, so there is no
     id to send — and another operator's user is untouched by anything
     done here. */
  it("touches nobody else's account", async () => {
    const before = await storedHash(otherUserId);
    await changePassword({ currentPassword: CURRENT, newPassword: REPLACEMENT });
    expect(await storedHash(otherUserId)).toBe(before);
  });

  it("refuses without a token", async () => {
    expect(
      (await app.inject({
        method: "POST", url: "/api/v1/auth/password",
        payload: { currentPassword: CURRENT, newPassword: REPLACEMENT },
      })).statusCode,
    ).toBe(401);
    expect(
      (await app.inject({ method: "PATCH", url: "/api/v1/auth/me", payload: { name: "X" } }))
        .statusCode,
    ).toBe(401);
  });
});
