/* ============================================================
   YOUR NAME, AND THE PASSWORD FOR THIS ACCOUNT.

   NEITHER OF THESE COULD BE CHANGED BY ANYBODY, AND THE SECOND ONE IS
   THE SERIOUS HALF.

   The administrator reset route ends its response with "Shown once.
   Hand it over directly and have them change it." There was no way to
   change it. A temporary password generated by an administrator and
   handed over in person WAS the permanent password of that account —
   the instruction had a wording and no mechanism, which is exactly the
   shape the demo-password rotation had before `--rotate` was written.

   It is worse here than there. That one was a demo. This is an
   operator's safety officer holding a credential a second person has
   seen and cannot stop knowing, on an account that reads every
   narrative filed by every reporter in the organisation.

   The name is the smaller half and it was equally absent: a person
   entered with a typo on the day the operator was seeded carried it on
   every report they filed and every disposition they recorded, for the
   life of the account, with nobody able to correct it.

   -------------------------------------------------------------
   THE CURRENT PASSWORD IS ASKED FOR, and it is not ceremony. An access
   token lives fifteen minutes and gets left behind on a shared handset
   in a ready room. A change-password form that trusts the token alone
   turns a borrowed screen into a permanent account takeover; proving
   the current password is what makes the person at the keyboard the
   account holder rather than whoever sat down next.

   -------------------------------------------------------------
   IT SAYS WHAT WILL HAPPEN BEFORE IT HAPPENS. Changing the password
   signs out every device including this one, and a form that did that
   silently would teach somebody not to change their password again.
   The warning is above the button, not in the response.

   -------------------------------------------------------------
   TWO FORMS, NOT ONE. A single form would make "fix a typo in my name"
   require typing a password, and the name is the change somebody makes
   casually. They also fail differently and must report differently —
   which is charter rule 8: a refused write is reported, and a form
   that reported one failure for two writes could not say which.
   ============================================================ */

import { html } from '../../shared/html.js';
import { authFetch, getSession } from '../../shared/session.js';

/** The minimum the API enforces. Stated here so the form can say it. */
const MIN_PASSWORD = 12;

async function fetchMe() {
  try {
    const res = await authFetch('/api/v1/auth/me');
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

export async function render(outlet) {
  const session = getSession() ?? {};

  /* SIGNED OUT IS NOT AN ERROR HERE, it is a different page. Somebody
     who followed a link or reopened a tab gets sent to sign in rather
     than shown a form that cannot submit. */
  if (!session.role) {
    outlet.innerHTML = html`
      <section class="panel wrap">
        <header class="page-head">
          <span class="eyebrow">Your account</span>
          <h1>Your profile</h1>
        </header>
        <p class="lede">
          Sign in to change your name or your password.
          <a href="/account">Go to sign in</a>.
        </p>
      </section>`.toString();
    return;
  }

  const me = await fetchMe();

  outlet.innerHTML = html`
    <section class="panel wrap">
      <header class="page-head">
        <span class="eyebrow">Your account</span>
        <h1>Your profile</h1>
        <p class="lede">
          Your name is what appears against every report you file and every
          disposition you record, so an auditor reading the record later is
          reading this.
        </p>
      </header>

      ${me
        ? ''
        : html`<p class="notice notice--error">
            Your current details could not be read from the safety office. You can
            still set a new name or password below; what is shown is not what is
            stored.
          </p>`}

      <form id="profile-form" class="card" novalidate>
        <label class="field">
          <span class="field-label">Your name</span>
          <input
            type="text" name="name" required minlength="2" maxlength="120"
            autocomplete="name" class="input-field" value="${me?.name ?? ''}"
          />
          <span class="field-hint">
            How you appear on the record. Two characters or more.
          </span>
        </label>

        <label class="field">
          <span class="field-label">Your email</span>
          <input type="email" class="input-field" value="${me?.email ?? ''}" disabled />
          <span class="field-hint">
            This is how you sign in and how an administrator resets your password,
            so changing it is an account migration rather than an edit. Ask your
            safety manager.
          </span>
        </label>

        <p class="hint" id="profile-status" role="status"></p>
        <button type="submit" class="btn btn-primary">Save your name</button>
      </form>
    </section>

    <section class="panel wrap">
      <h2>Change your password</h2>
      <p class="lede lede--tight">
        If an administrator issued you a temporary password, change it here.
      </p>

      <form id="password-form" class="card" novalidate>
        <label class="field">
          <span class="field-label">Your current password *</span>
          <input
            type="password" name="currentPassword" required
            autocomplete="current-password" class="input-field"
          />
          <span class="field-hint">
            Asked for because a signed-in screen can be left open on a shared
            handset, and the current password is what proves this is your account.
          </span>
        </label>

        <label class="field">
          <span class="field-label">Your new password *</span>
          <input
            type="password" name="newPassword" required minlength="${MIN_PASSWORD}"
            autocomplete="new-password" class="input-field"
          />
          <span class="field-hint">
            ${MIN_PASSWORD} characters or more. Length beats punctuation — a phrase
            you will remember is stronger than a short string you will write down.
          </span>
        </label>

        <p class="notice">
          <strong>This signs out every device, including this one.</strong> That is
          the point of changing a password somebody else may know. You can carry on
          here until this session expires, then sign in with the new one.
        </p>

        <p class="hint" id="password-status" role="status"></p>
        <button type="submit" class="btn btn-primary">Change password</button>
      </form>
    </section>
  `.toString();

  wireName(outlet);
  wirePassword(outlet);
}

/* ------------------------------------------------------------------
   CHARTER RULE 8 IN BOTH HANDLERS: a write that did not happen is
   reported, never swallowed. The button re-enables in `finally` so a
   failed save leaves a form somebody can try again from rather than a
   dead control.
   ------------------------------------------------------------------ */

function wireName(outlet) {
  const form = outlet.querySelector('#profile-form');
  const status = outlet.querySelector('#profile-status');

  form.addEventListener('submit', async (event) => {
    event.preventDefault();
    const name = form.elements.name.value.trim();
    if (name.length < 2) {
      status.textContent = 'A name needs at least two characters.';
      return;
    }

    const button = form.querySelector('button[type=submit]');
    button.disabled = true;
    status.textContent = 'Saving…';
    try {
      const res = await authFetch('/api/v1/auth/me', {
        method: 'PATCH',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ name })
      });
      const body = await res.json().catch(() => ({}));
      status.textContent = res.ok
        ? 'Saved. New reports and dispositions will carry this name.'
        : body.message ??
          'That was not accepted, and your name has not changed. Check the field and try again.';
    } catch {
      status.textContent =
        'The safety office could not be reached, and your name has not changed.';
    } finally {
      button.disabled = false;
    }
  });
}

function wirePassword(outlet) {
  const form = outlet.querySelector('#password-form');
  const status = outlet.querySelector('#password-status');

  form.addEventListener('submit', async (event) => {
    event.preventDefault();
    const currentPassword = form.elements.currentPassword.value;
    const newPassword = form.elements.newPassword.value;

    /* CHECKED HERE AS WELL AS ON THE SERVER, so somebody is told before
       they send rather than after — and the server refuses regardless,
       because a client-side floor is a convenience and never a rule. */
    if (newPassword.length < MIN_PASSWORD) {
      status.textContent = `The new password needs ${MIN_PASSWORD} characters or more.`;
      return;
    }
    if (currentPassword === newPassword) {
      status.textContent =
        'The new password is the same as the current one. If you are changing it ' +
        'because somebody else knows it, it needs to be different.';
      return;
    }

    const button = form.querySelector('button[type=submit]');
    button.disabled = true;
    status.textContent = 'Changing…';
    try {
      const res = await authFetch('/api/v1/auth/password', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ currentPassword, newPassword })
      });
      const body = await res.json().catch(() => ({}));
      if (res.ok) {
        /* CLEARED ON SUCCESS. A password left sitting in a field on a
           screen that has just been described as possibly shared is the
           thing this whole form exists to get away from. */
        form.reset();
        status.textContent =
          body.message ?? 'Password changed. Every device has been signed out.';
        return;
      }
      status.textContent =
        body.message ??
        'That was not accepted, and your password has not changed.';
    } catch {
      status.textContent =
        'The safety office could not be reached, and your password has not changed.';
    } finally {
      button.disabled = false;
    }
  });
}
