-- ONE REDUNDANT INDEX, AND THE FIVE STATEMENTS THAT USED TO BE HERE.
--
-- `prisma migrate dev` proposed this alongside an unrelated feature,
-- which is how a schema change nobody intended ships under a name
-- nobody questions. It was split out so its name says what it does —
-- and splitting it is the only reason the rest of it did not ship.
--
-- WHAT SURVIVED: VoluntaryScheme_orgId_idx
--
--   Created by 20260815091500_index_reconciliation. schema.prisma now
--   carries an explicit comment on that model saying there is NO
--   @@index([orgId]) because orgId is already @unique, so the index is
--   drift from a decision later reversed in the schema and never in the
--   database. Measured against production, which carries BOTH:
--     VoluntaryScheme_orgId_key  UNIQUE btree ("orgId")
--     VoluntaryScheme_orgId_idx         btree ("orgId")
--   The unique index serves every lookup the plain one would, so this
--   drops dead weight on every write and no read path loses an index.
--
-- WHAT WAS REMOVED, AND WHY THAT MATTERS MORE
--
--   This migration also carried five ALTER COLUMN ... DROP DEFAULT
--   statements against Org.fleetTypes, Org.bases, Org.operationTypes,
--   OrgConfig.aerodromes, OrgConfig.aircraftTypes and
--   SafetyReport.cicttCodes. The comment justifying them said Prisma
--   supplies the value on every insert it makes, so the database-side
--   DEFAULT was unreachable from this product.
--
--   THAT WAS FALSE, and the integration suite proved it in one line.
--   Prisma OMITS a scalar list it was not given and relies on the
--   column default; drop the default and the column is NOT NULL with
--   nothing to fall back on. Driven directly against Postgres:
--
--     insert into "Org" (id,name,jurisdiction,"trialEndsOn") values (...)
--     ERROR: null value in column "fleetTypes" violates not-null constraint
--
--   Twenty-nine auth integration tests went red at once, every one of
--   them on org.create in a beforeEach. Shipped, it would have made
--   creating an operator impossible in production.
--
--   The empty-array default is Prisma's own convention for a scalar
--   list — created at the database and not declared in the schema — so
--   `migrate diff` proposing to drop it is an artefact of that
--   asymmetry rather than real drift. It will be proposed again. Do not
--   accept it.

-- DropIndex
-- IF EXISTS, matching 20260815091500_index_reconciliation, which created
-- this same index with CREATE INDEX IF NOT EXISTS. A migration that dies
-- on an environment where the object is already gone blocks every later
-- migration behind it.
DROP INDEX IF EXISTS "VoluntaryScheme_orgId_idx";
